#!/usr/bin/env bash
# Records one video per tutorial section: for each step in
# TUTORIAL_VIDEO_STEPS, builds a fresh scene, replays every earlier step off
# screen so the recording starts where the page's prose says it does, writes
# a tape, and renders it to docs/assets/tutorial/<step>.gif and .webm.
#
#   scripts/docs/tutorial-tapes.sh                every video
#   scripts/docs/tutorial-tapes.sh start-work     one of them
#   scripts/docs/tutorial-tapes.sh --check        no rendering: replay every
#                                                 step and fail on a command
#                                                 that no longer works
#
# The commands come from scripts/docs/tutorial-steps.sh, the same file the
# page's transcripts come from, and the terminal settings are read out of
# scripts/docs/demo.tape, so the videos cannot drift from either. Only
# --check runs in CI; rendering wants vhs, ttyd, ffmpeg and a headless
# chromium, and is something a release does by hand.
#
# FF names the binary under test; default is `ff` on PATH.
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
# Relative to the repository root, which is where vhs is invoked: its tape
# parser does not take an absolute path on an Output line.
OUT_REL="docs/assets/tutorial"
OUT_DIR="$ROOT_DIR/$OUT_REL"
TAPE_DIR="$ROOT_DIR/target/docs-tapes"

FF="${FF:-ff}"

export GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null GIT_CONFIG_NOSYSTEM=1
export GIT_EDITOR=false EDITOR=false

# shellcheck source=scripts/docs/tutorial-steps.sh
. "$ROOT_DIR/scripts/docs/tutorial-steps.sh"

check=false
if [ "${1:-}" = --check ]; then
  check=true
  shift
fi

steps=("$@")
[ ${#steps[@]} -gt 0 ] || steps=("${TUTORIAL_VIDEO_STEPS[@]}")

tutorial_put_ff_on_path "$FF"

# One scene per recording. A step's video opens on the state its section
# opens on, which is every earlier step run for its effect and nothing of
# them on screen.
scene_up_to() {
  local target=$1 scene step
  scene=$(mktemp -d)
  tutorial_origin "$scene" "$ROOT_DIR"
  (
    SCENE=$scene
    cd "$scene"
    for step in "${TUTORIAL_STEPS[@]}"; do
      if [ "$step" = "$target" ]; then
        # The step's own machinery — a teammate landing a commit — belongs
        # to the state the recording opens on, not to the recording.
        tutorial_run_step "$step" setup
        break
      fi
      tutorial_run_step "$step" quiet
    done
    # Where the earlier steps left off, which is the directory the tape cds
    # into.
    pwd > "$scene/.cwd"
  )
  printf '%s\n' "$scene"
}

# --- the check: every step, in order, with nothing recorded ---
if $check; then
  scene=$(mktemp -d)
  trap 'rm -rf "$scene" "${TUTORIAL_BIN_DIR:-}"' EXIT
  tutorial_origin "$scene" "$ROOT_DIR"
  (
    SCENE=$scene
    cd "$scene"
    for step in "${TUTORIAL_STEPS[@]}"; do
      tutorial_run_step "$step" check || {
        echo "tutorial step '$step' no longer runs clean" >&2
        exit 1
      }
    done
  )
  echo "every tutorial step runs"
  exit 0
fi

command -v vhs >/dev/null || { echo "vhs is not on PATH: see scripts/docs/demo.tape" >&2; exit 1; }

mkdir -p "$OUT_DIR" "$TAPE_DIR"

# The terminal settings are demo.tape's, read from it rather than repeated
# here, so every recording in the docs looks like one machine.
settings=$(grep '^Set ' "$ROOT_DIR/scripts/docs/demo.tape")

for step in "${steps[@]}"; do
  scene=$(scene_up_to "$step")
  cwd=$(cat "$scene/.cwd")
  tape="$TAPE_DIR/$step.tape"

  {
    printf '# Generated by scripts/docs/tutorial-tapes.sh — edit the step in\n'
    printf '# scripts/docs/tutorial-steps.sh, not this file.\n\n'
    printf 'Output %s/%s.gif\n' "$OUT_REL" "$step"
    printf 'Output %s/%s.webm\n\n' "$OUT_REL" "$step"
    printf 'Require ff\n\n'
    printf '%s\n\n' "$settings"

    printf 'Hide\n'
    printf 'Type `export GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null GIT_CONFIG_NOSYSTEM=1 GIT_EDITOR=false EDITOR=false` Enter\n'
    printf 'Type `cd %s` Enter\n' "$cwd"
    printf "Type \`PS1='\\\\n\\\\[\\\\e[38;5;114m\\\\]\$\\\\[\\\\e[0m\\\\] ' && unset PROMPT_COMMAND && clear\` Enter\n"
    printf 'Sleep 1s\n'
    printf 'Show\n\n'
    printf 'Sleep 800ms\n'

    # The step's own lines, asked for from inside the scene and with SCENE
    # set: a step looks up the branch `ff start` minted and the commit an
    # absorb aims at in the repository in front of it, and that repository
    # is the scene, never this one.
    local_lines=$(cd "$cwd" && SCENE=$scene tutorial_step_lines "$step")
    while IFS= read -r line; do
      tag=${line%%|*}
      cmd=${line#*|}
      case "$tag" in
        set) ;;
        note) printf 'Type `%s` Enter Sleep 900ms\n' "$cmd" ;;
        edit) printf 'Type `%s` Sleep 200ms Enter Sleep 500ms\n' "$cmd" ;;
        cont) printf 'Type `%s` Sleep 100ms Enter Sleep 300ms\n' "$cmd" ;;
        run|video) printf 'Type `%s` Sleep 400ms Enter Sleep 2500ms\n' "$cmd" ;;
      esac
    done <<< "$local_lines"

    printf 'Sleep 2s\n'
  } > "$tape"

  echo "rendering $step"
  ( SCENE=$scene; cd "$ROOT_DIR" && vhs "$tape" >/dev/null )
  rm -rf "$scene"
done

rm -rf "${TUTORIAL_BIN_DIR:-}"
echo "wrote ${#steps[@]} recording(s) to $OUT_DIR"
